name: CI/CD Pipeline

on:
  push:
    paths:
      - 'tinyurl/**'
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java and Maven
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21' # or your project's Java version
          distribution: 'temurin'  

      # Step 3: Build the application and run unit tests
      - name: Build and test
        run: |
          cd tinyurl
          mvn clean install

  load-test:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Start the application
      - name: Start Spring Boot application
        run: mvn spring-boot:run &
        env:
          SPRING_PROFILES_ACTIVE: test
          SERVER_PORT: 8080 # Ensure it matches your application config

      # Step 3: Run JMeter load tests
      - name: Run load tests
        uses: rbhadti94/apache-jmeter-action@v0.7.0
        with:
          testFilePath: tinyurl/src/main/resources/loadtesting/jmeter/loadtest.jmx # Path to your JMeter test file
          outputReportsFolder: reports/

      # Step 4: Stop the application
      - name: Stop Spring Boot application
        run: mvn spring-boot:stop
         

  notify:
    needs: [build-and-test, load-test]
    runs-on: ubuntu-latest

    steps:
      - name: Notify team
        run: echo "CI/CD Pipeline completed successfully!"
